#!/usr/bin/env bash
# Installs and setup haproxy

apt-get update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Ensure the configuration file exists
touch /etc/haproxy/haproxy.cfg

# Listen to web1 and web2 servers
echo "
   frontend http_front
      bind *:80
      default_backend http_back

   backend http_back
      balance roundrobin
      server 188912-web-01 54.210.50.223:80 check
      server 188912-web-02 34.229.255.109:80 check
" >> /etc/haproxy/haproxy.cfg

systemctl enable haproxy
systemctl start haproxy