#!/usr/bin/env bash
# This script is displaying FuzzBuzz when number is a multiple of 3 and 5
# Fizz when number is a multiple of 3
# Buzz when number is a multiple of 5
# Otherwise displays the number in a list format

for ((i = 1; i <= 100; i++))
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $i
    fi
done
