#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop, but for the 9th iteration display Hi

i=1
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
