#!/usr/bin/env bash
# This script displays 4 and then bad luck from China for the 4th loop iteration
# and displays 9 and then bad luck from Japan for the 9th loop iteration
# and displays 17 and then bad luck from Italy for the 17th loop iteration
# use while loop
# use case statement

i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    (( i++ ))
done
