#!/usr/bin/env bash
# Bash script that displays the time from 12 hours and 59 minutes
# Display hours from 0 to 12
# Display minutes from 1 to 59
# use while loop

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hour++ ))
done
